### ISSUE TITLE
com.oneops.search.msg.processor.es.ESMessageProcessor - >>>>>>>>Error in processMessage() ESMessageProcessor

### ISSUE THREAD

**Issue by yrmallu** [oneops/search#29]
@bannama @kinjal-brahmbhatt 

2017-05-25 09:10:18 [main] INFO com.oneops.util.DNSUtil - Resolving host name: localhost...
2017-05-25 09:10:18 [main] WARN com.oneops.util.DNSUtil - Skipping IPv6 address: 0:0:0:0:0:0:0:1
2017-05-25 09:10:18 [main] INFO com.oneops.util.DNSUtil - Resolved host address for [localhost] is [127.0.0.1]
2017-05-25 09:10:18 [main] INFO com.oneops.util.AMQConnectorURI - AMQ broker URL for localhost: failover:(tcp://127.0.0.1:61616?keepAlive=true)?initialReconnectDelay=1000&maxReconnectDelay=30000&maxReconnectAttempts=-1&backup=false&randomize=false&jms.prefetchPolicy.queuePrefetch=10&jms.redeliveryPolicy.maximumRedeliveries=10000&jms.redeliveryPolicy.initialRedeliveryDelay=3000&jms.redeliveryPolicy.useExponentialBackOff=true&jms.redeliveryPolicy.backOffMultiplier=2
2017-05-25 09:10:19 [main] INFO org.elasticsearch.plugins - [Forbush Man] loaded [], sites []
2017-05-25 09:10:19 [main] INFO org.springframework.data.elasticsearch.client.TransportClientFactoryBean - adding transport node : localhost:9300
2017-05-25 09:10:19 [main] INFO org.springframework.context.support.DefaultLifecycleProcessor - Starting beans in phase 2147483647
2017-05-25 09:11:20 [listenerContainer-9] ERROR com.oneops.search.msg.processor.es.ESMessageProcessor - >>>>>>>>Error in processMessage() ESMessageProcessor for type :cm_ci::msgId :null::EngineClosedException: [cms-all][0] CurrentState[CLOSED]
org.elasticsearch.index.engine.EngineClosedException: [cms-all][0] CurrentState[CLOSED]
        at org.elasticsearch.index.engine.Engine.ensureOpen(Engine.java:289)
        at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:358)
        at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:510)
        at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:196)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase.performOnPrimary(TransportShardReplicationOperationAction.java:574)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase$1.doRun(TransportShardReplicationOperationAction.java:440)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by mosabua** [comment]
Issue tracking is migrated to Walmart JIRA and https://github.com/oneops/oneops.
